"""Correlate and parameterize without recorded responses (LoadRunner VuGen's scan after a replay).

A .jmx file, or a HAR saved without response bodies, holds the requests but not what the
server answered, so the import cannot see where dynamic values come from. A replay can: the
server answers again, with fresh values. For every value the script still sends as recorded
that looks dynamic, the earlier replay responses are searched, closest first:

  * by value: the recorded value itself (the server issued the same value again);
  * by name: the same field (form input, meta tag, JSON key, link, header or cookie) holding a
    value of the same shape, i.e. the fresh value that replaced the recorded one.

The value found decides how it is extracted (JSON path, boundaries or a header expression),
exactly as for HAR recordings, and the recorded value is replaced with ${variable} in the
requests after it. Values that no response holds were generated by the browser: single-use
UUIDs and timestamps become generated parameters, the rest are offered as suggestions.

Recorded logins (a user-name field and a password field in one request) become a data file
with the recorded account as its first row, so more test accounts are one CSV row each.
"""
from __future__ import annotations

import csv
import io
import json
import re
import time
import xml.etree.ElementTree as ET
from typing import Any, Iterator
from urllib.parse import parse_qsl, urlsplit

from ..models.script import CorrelationRule, DataFile, Parameter, Replacement, ScriptDesign
from .correlation import (MAX_CANDIDATES, MAX_SEARCH_CHARS, _UUID, _extractor, _request_values, looks_dynamic,
                          mask, replace_value, variable_name, walk_json)

SEARCH_BUDGET_CHARS = 1_000_000_000
MAX_PAIRS = 20_000                       # named values read from one response
_LABEL = re.compile(r"^#(\d+) ")
_SKIP_HEADERS = {"cookie", "host", "content-length", "connection"}
_TAG = re.compile(r"<(?:input|meta)\b[^>]*>", re.IGNORECASE)
_ATTR = re.compile(r"""([A-Za-z_:][-\w:.]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+))""")
_PAIR = re.compile(r"""["']?([A-Za-z_$][\w$-]{0,63})["']?\s*[:=]\s*["']([^"'\\\s]{1,4096})["']""")
_LINK = re.compile(r"""[?&;]([A-Za-z_][\w.\-\[\]]{0,63})=([^&"'\s<>#]{1,4096})""")
_HEX = re.compile(r"^[0-9a-fA-F]+$")
_JWT = re.compile(r"^[\w-]+\.[\w-]+\.[\w-]*$")
_CSRF_NAMES = {"csrf", "csrftoken", "xsrf", "xsrftoken", "csrfmiddlewaretoken", "authenticitytoken",
               "requestverificationtoken", "antiforgerytoken", "antiforgery"}
_GENERIC_FIELDS = {"id", "value", "data", "result", "token"}
_USER_FIELDS = {"username", "user", "userid", "login", "loginid", "loginname", "email", "emailaddress", "mail",
                "jusername", "uname", "account", "accountname"}
_PASSWORD_FIELDS = {"password", "pass", "passwd", "pwd", "jpassword", "passcode", "userpassword", "loginpassword"}
_SEARCH_FIELDS = {"q", "query", "search", "searchterm", "searchtext", "keyword", "keywords", "term", "text"}


# ---- what the script sends ----------------------------------------------------------------------

def _child_text(el: ET.Element, name: str) -> str:
    for child in el:
        if child.get("name") == name:
            return child.text or ""
    return ""


def sampler_request(sampler: ET.Element, sub: ET.Element) -> dict[str, Any]:
    """The request a plan's HTTP sampler sends, read from its properties and its Header Managers."""
    raw = _child_text(sampler, "HTTPSampler.postBodyRaw").strip().lower() == "true"
    args: list[tuple[str, str]] = []
    for arg in sampler.iter("elementProp"):
        if arg.get("elementType") == "HTTPArgument":
            name, value = arg.find("stringProp[@name='Argument.name']"), arg.find("stringProp[@name='Argument.value']")
            args.append((((name.text if name is not None else arg.get("name")) or ""),
                         (value.text or "") if value is not None else ""))
    headers = []
    for manager in (c for c in sub if c.tag == "HeaderManager"):
        for header in manager.iter("elementProp"):
            name, value = header.find("stringProp[@name='Header.name']"), header.find("stringProp[@name='Header.value']")
            if name is not None and name.text:
                headers.append([name.text, (value.text or "") if value is not None else ""])
    return {"method": (_child_text(sampler, "HTTPSampler.method") or "GET").upper(),
            "path": _child_text(sampler, "HTTPSampler.path"), "body": args[0][1] if raw and args else None,
            "args": [] if raw else args, "headers": headers}


def script_requests(tree: Any, order: list[int]) -> list[dict[str, Any]]:
    """Requests of a built plan (script_builder.build_tree), in run order, as the script sends them."""
    return [{"index": index, **sampler_request(*tree.samplers[index][:2])} for index in order if index in tree.samplers]


def _url(path: str) -> str:
    if re.match(r"^https?://", path, re.IGNORECASE):
        return path
    return "http://host" + (path if path.startswith("/") else "/" + path)


def request_fields(req: dict[str, Any]) -> Iterator[tuple[str, str]]:
    """(value, field name) for everything a request sends: URL, form or JSON fields, headers."""
    headers = [h for h in req["headers"] if h[0].lower() not in _SKIP_HEADERS]
    yield from _request_values({"url": _url(req["path"]), "body": req["body"], "headers": headers})
    for name, value in req["args"]:
        if value:
            yield value, name or "value"


def request_text(req: dict[str, Any]) -> str:
    return "\n".join([req["path"], req["body"] or "", *(v for _, v in req["args"]), *(v for _, v in req["headers"])])


# ---- what the replay received -------------------------------------------------------------------

def replay_responses(samples: list[dict[str, Any]]) -> dict[int, dict[str, Any]]:
    """Request index -> what the replay sent and received (debug_runner.parse_results samples)."""
    out: dict[int, dict[str, Any]] = {}
    for s in samples:
        m = _LABEL.match(s["label"])
        if not m or int(m.group(1)) in out:
            continue
        headers = []
        for line in (s["response_headers"] or "").splitlines():
            name, sep, value = line.partition(":")
            if sep and name.strip() and " " not in name.strip():
                headers.append([name.strip(), value.strip()])
        mime = next((v.split(";")[0].strip().lower() for n, v in headers if n.lower() == "content-type"), "")
        status = s["status"] or ""
        out[int(m.group(1))] = {
            "ok": status.isdigit() and int(status) < 400, "status": status,
            "sent": "\n".join([s["url"] or "", s["request_body"] or "", s["request_headers"] or ""]),
            "body": (s["response_body"] or "")[:MAX_SEARCH_CHARS] or None, "mime": mime, "headers": headers,
        }
    return out


def named_values(resp: dict[str, Any]) -> list[tuple[str, str]]:
    """(name, value) pairs a response offers: JSON fields, form inputs and meta tags, script
    assignments, link parameters, headers and cookies."""
    pairs: list[tuple[str, str]] = []
    body = resp.get("body") or ""
    if body:
        if "json" in resp.get("mime", "") or body.lstrip()[:1] in ("{", "["):
            try:
                pairs += [(key, value) for _, key, value in walk_json(json.loads(body)) if key]
            except ValueError:
                pass
        if "<" in body:
            for tag in _TAG.finditer(body):
                attrs = {m.group(1).lower(): next(g for g in m.groups()[1:] if g is not None)
                         for m in _ATTR.finditer(tag.group(0))}
                name, value = attrs.get("name") or attrs.get("id"), attrs.get("value", attrs.get("content"))
                if name and value:
                    pairs.append((name, value))
        pairs += [(m.group(1), m.group(2)) for m in _PAIR.finditer(body)]
        pairs += [(m.group(1), m.group(2)) for m in _LINK.finditer(body)]
    for name, value in resp.get("headers") or []:
        low = name.lower()
        if low == "set-cookie":
            cookie, _, rest = value.partition("=")
            pairs.append((cookie.strip(), rest.split(";")[0].strip()))
        elif low == "location":
            pairs += parse_qsl(urlsplit(value).query)
        else:
            pairs.append((name, value))
    return pairs[:MAX_PAIRS]


# ---- matching a recorded value with a fresh one ----------------------------------------------------

def _key(name: str) -> str:
    """Compare names without case, separators or an x- prefix: X-CSRF-Token, csrf-token, csrf_token."""
    return re.sub(r"[^a-z0-9]", "", re.sub(r"^x[-_]", "", name.strip().lower()))


def name_matches(request_name: str, response_name: str) -> bool:
    a, b = _key(request_name), _key(response_name)
    if not a or not b:
        return False
    if a == b or (a in _CSRF_NAMES and b in _CSRF_NAMES):
        return True
    if a == "token":                                   # Authorization: Bearer <token>, or a field "token"
        return (b.endswith("token") and "refresh" not in b) or b in {"jwt", "bearer", "authorization"}
    if request_name.endswith("_id") and a.endswith("id"):     # a path segment after /orders/ -> "orders_id"
        stem = a[:-2]
        return b in {"id", "uuid", stem + "id", stem.rstrip("s") + "id", stem.rstrip("s") + "uuid"}
    return a.endswith("id") and len(a) > 2 and b == "id"


def _shape(value: str) -> str:
    if _UUID.match(value):
        return "uuid"
    if value.isdigit():
        return "digits"
    if _JWT.match(value) and value.count(".") == 2:
        return "jwt"
    return "hex" if _HEX.match(value) else "token"


def similar(recorded: str, found: str) -> bool:
    """Could `found` be a fresh copy of `recorded`: the same kind of value, a comparable length."""
    a, b = _shape(recorded), _shape(found)
    if a != b and {a, b} != {"hex", "token"}:
        return False
    if a == "jwt":
        return True
    if a == "digits":
        return abs(len(found) - len(recorded)) <= 3
    return 0.5 <= len(found) / len(recorded) <= 2


def _fresh_value(value: str, name: str, pairs: list[tuple[str, str]]) -> str | None:
    for key, found in pairs:
        if found != value and name_matches(name, key) and looks_dynamic(found) and similar(value, found):
            return found
    return None


def _in_response(value: str, resp: dict[str, Any]) -> bool:
    return bool(resp.get("body") and value in resp["body"]) or any(value in v for _, v in resp.get("headers") or [])


def _generated_kind(value: str) -> str:
    if _UUID.match(value):
        return "uuid"
    if value.isdigit() and len(value) in (10, 13):
        stamp_ms = int(value) * (1000 if len(value) == 10 else 1)
        if 946_684_800_000 <= stamp_ms <= (time.time() + 2 * 86_400) * 1000:      # 2000-01-01 .. now
            return "timestamp"
    return "value"


def scan(requests: list[dict[str, Any]], replay: dict[int, dict[str, Any]], taken: set[str]) -> dict[str, Any]:
    """Find the sources of the dynamic values the script still sends as recorded.

    Returns {"correlations": [rules], "generated": [values no response holds], "unknown": count of
    values whose earlier requests did not all succeed in the replay (try again after fixing them)}.
    `taken`: variable names in use (lower case); names given here are added to it.
    """
    order = [r["index"] for r in requests]
    position = {index: n for n, index in enumerate(order)}
    texts = {r["index"]: request_text(r) for r in requests}
    first_use: dict[str, tuple[int, str]] = {}
    for req in requests:
        for value, name in request_fields(req):
            if value not in first_use and looks_dynamic(value):
                first_use[value] = (req["index"], name)
                if len(first_use) >= MAX_CANDIDATES:
                    break

    pairs_cache: dict[int, list[tuple[str, str]]] = {}
    correlations: list[dict[str, Any]] = []
    generated: list[dict[str, Any]] = []
    unknown = 0
    budget = SEARCH_BUDGET_CHARS
    # Longest first, so a value that contains another is replaced whole.
    for value, (use, name) in sorted(first_use.items(), key=lambda kv: (-len(kv[0]), position[kv[1][0]])):
        if value not in texts[use]:
            continue                                   # replaced already, as part of a longer value
        found = None
        for source in reversed(order[:position[use]]):
            resp = replay.get(source)
            if resp is None:
                continue
            budget -= len(resp.get("body") or "")
            if budget < 0:
                break
            fresh = value if _in_response(value, resp) and value not in resp["sent"] else None
            if fresh is None:
                pairs = pairs_cache.setdefault(source, named_values(resp))
                fresh = _fresh_value(value, name, pairs)
            rule = _extractor(fresh, resp.get("body"), resp.get("mime", ""), resp.get("headers") or []) if fresh else None
            if rule:
                found = (source, rule)
                break
        if found:
            source, rule = found
            field = rule.pop("field")
            generic = not field or (field.lower() in _GENERIC_FIELDS and name != "value")
            variable = variable_name(name if generic else field, taken)
            used_in = []
            for index in order[position[source] + 1:]:
                texts[index], count = replace_value(texts[index], value, variable)
                if count:
                    used_in.append(index)
            correlations.append({"variable": variable, "source": source, **rule, "match": 1, "replace": value,
                                 "origin": "auto", "preview": mask(value), "used_in": used_in})
            continue
        earlier = order[:position[use]]
        if use in replay and all(i in replay and replay[i]["ok"] for i in earlier):
            kind = _generated_kind(value)
            generated.append({"name": name, "preview": mask(value), "first_used": use, "kind": kind,
                              "value": value if kind in ("uuid", "timestamp") else None,
                              "uses": sum(1 for i in order if replace_value(texts[i], value, "x")[1])})
        else:
            unknown += 1
    correlations.sort(key=lambda c: (position.get(c["source"], 0), c["variable"]))
    return {"correlations": correlations, "generated": generated, "unknown": unknown}


# ---- parameters ---------------------------------------------------------------------------------

def generated_parameters(values: list[dict[str, Any]], taken: set[str]) -> tuple[list[dict], list[dict], list[dict]]:
    """Single-use browser UUIDs and timestamps become generated parameters (a new value every time).

    Returns (parameters, replacements, the values left as suggestions).
    """
    parameters, replacements, left = [], [], []
    for v in values:
        if v.get("value") and v["kind"] in ("uuid", "timestamp") and v.get("uses", 1) == 1:
            name = variable_name(v["name"], taken)
            parameters.append({"name": name, "type": "uuid"} if v["kind"] == "uuid" else
                              {"name": name, "type": "date", "format": "epoch_ms" if len(v["value"]) == 13 else "epoch_s"})
            replacements.append({"find": v["value"], "variable": name})
        else:
            left.append({k: v[k] for k in ("name", "preview", "first_used", "kind", "value") if k in v})
    return parameters, replacements, left


def _occurrences(requests: list[dict[str, Any]], value: str) -> int:
    return sum(replace_value(request_text(r), value, "x")[1] for r in requests)


def find_login(requests: list[dict[str, Any]]) -> dict[str, Any] | None:
    """The first request that sends a user-name field and a password field.

    It is marked unsafe when either value also occurs outside such fields (a user name "admin"
    in a /admin/ path, say): replacing it everywhere would change those requests too.
    """
    for req in requests:
        fields = [(value, name) for value, name in request_fields(req) if value and "${" not in value]
        user = next(((v, n) for v, n in fields if _key(n) in _USER_FIELDS), None)
        password = next(((v, n) for v, n in fields if _key(n) in _PASSWORD_FIELDS), None)
        if not user or not password or user[0] == password[0] or len(user[0]) < 3 or len(password[0]) < 3:
            continue
        in_fields = {v: sum(1 for r in requests for value, n in request_fields(r)
                            if value == v and _key(n) in (_USER_FIELDS | _PASSWORD_FIELDS)) for v in (user[0], password[0])}
        if all(_occurrences(requests, v) <= count for v, count in in_fields.items()):
            return {"index": req["index"], "username": user[0], "password": password[0],
                    "fields": [user[1], password[1]]}
        return {"index": req["index"], "unsafe": True, "fields": [user[1], password[1]]}
    return None


def login_data_file(login: dict[str, Any], taken: set[str]) -> tuple[dict, bytes, list[dict]] | None:
    """users.csv holding the recorded account, and the replacements that use it."""
    if login.get("unsafe") or {"username", "password"} & taken:
        return None
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerows([["username", "password"], [login["username"], login["password"]]])
    taken.update({"username", "password"})
    data_file = {"name": "users.csv", "columns": ["username", "password"], "rows": 1, "sharing": "all"}
    return data_file, buf.getvalue().encode(), [{"find": login["username"], "variable": "username"},
                                                {"find": login["password"], "variable": "password"}]


def search_suggestions(requests: list[dict[str, Any]], taken: set[str]) -> list[dict[str, Any]]:
    """Search terms and similar user input: offered as list parameters (not applied)."""
    out, seen = [], set()
    for req in requests:
        for value, name in request_fields(req):
            if _key(name) in _SEARCH_FIELDS and value and "${" not in value and len(value) <= 200 and value not in seen:
                seen.add(value)
                out.append({"name": variable_name(name, set(taken)), "preview": value, "first_used": req["index"],
                            "kind": "search", "value": value})
    return out


# ---- adding what was found to a design ------------------------------------------------------------

def design_names(design: dict[str, Any], placeholders: list[str] = ()) -> set[str]:
    d = ScriptDesign(**design)
    return ({c.variable.lower() for c in d.correlations} | {p.name.lower() for p in d.parameters}
            | {c.lower() for f in d.data_files for c in f.columns} | {v.lower() for v in placeholders})


def merge(design: dict[str, Any], *, correlations: list[dict] = (), parameters: list[dict] = (),
          replacements: list[dict] = (), data_files: list[dict] = ()) -> tuple[dict[str, Any], dict[str, list[str]]]:
    """Add found parts to a design. Parts that clash with it or fail validation are left out."""
    current = ScriptDesign(**design)
    names = design_names(design)
    replaced = {c.replace for c in current.correlations if c.replace} | {r.find for r in current.replacements}
    added: dict[str, list[str]] = {"correlations": [], "parameters": [], "data_files": []}

    def valid(model: type, data: dict) -> Any:
        try:
            return model(**data)
        except ValueError:
            return None

    for raw in correlations:
        rule = valid(CorrelationRule, raw)
        if rule and rule.variable.lower() not in names and rule.replace not in replaced:
            current.correlations.append(rule)
            names.add(rule.variable.lower())
            replaced.add(rule.replace)
            added["correlations"].append(rule.variable)
    for raw in data_files:
        f = valid(DataFile, raw)
        if f and not {c.lower() for c in f.columns} & names and all(x.name != f.name for x in current.data_files):
            current.data_files.append(f)
            names.update(c.lower() for c in f.columns)
            added["data_files"].append(f.name)
    for raw in parameters:
        p = valid(Parameter, raw)
        if p and p.name.lower() not in names:
            current.parameters.append(p)
            names.add(p.name.lower())
            added["parameters"].append(p.name)
    for raw in replacements:
        r = valid(Replacement, raw)
        if r and r.variable.lower() in names and r.find not in replaced:
            current.replacements.append(r)
            replaced.add(r.find)
    return ScriptDesign(**current.model_dump()).model_dump(), added
